### PR TITLE
App and filter design

### PR DESCRIPTION
**Pull request by steveoh**
Please advise on design and filter wireframes. I am happy to make minor changes.

We can merge this and then create more issues specific to the assumptions and omissions I made from the user stories.

The website is on [test](https://test.mapserv.utah.gov/app).

image

image

image

labels collapse calendars
image

image

---

refs #8
refs #9
refs #10
refs #11
refs #12

### CODE REVIEW

**Comment by stdavis** [comment]
Don't forget about the changelog.

Yeah for hooks!

Are the number of options in the name dropdown going to be unwieldy? Maybe they should be changed to a typeahead?

The horizontal scrolling on the different filter tabs feels a little janky to me. Maybe make the sidebar wider or switch them to pills and wrap?

**Comment by steveoh** [comment]
> Are the number of options in the name dropdown going to be unwieldy? Maybe they should be changed to a typeahead?

Are you referencing the Agent tab? If so I don't understand how that is supposed to function based on the current requirements. I agree, a drop down is probably not a great idea.

**Comment by nathankota** [comment]
This is looking great so far. 

> The horizontal scrolling on the different filter tabs feels a little janky to me. Maybe make the sidebar wider or switch them to pills and wrap?
I concur with the sidebar being slightly wider to accommodate for that last "Other" filter.

> Are you referencing the Agent tab? If so I don't understand how that is supposed to function based on the current requirements. I agree, a drop down is probably not a great idea.
Client feedback request per #8

**Comment by steveoh** [comment]
ok, changes made and pushed to test... any other changes required for approvals?

**Pull request merged**
