### PR TITLE
Offender CSV

### LINKED ISSUE #56: csv download
After a filter has been applied, users would like a "download" button to download a csv of the filter results. The csv should include [all attributes](https://github.com/agrc/parole-and-probation/wiki/Database-Fields) for returned offender records.

### PR DESCRIPTION
**Pull request by steveoh**
Added a button that will turn blue if it works or red if it failed or no color if there was nothing to export for 10 seconds.

image
image
image

When the download is successful and if the browser supports the api's necessary the csv will download...

image

It will also send an email in case the api's are not supported.

image

closes #56

### CODE REVIEW

**Comment by nathankota** [comment]
I don't experience the blue or red buttons, but download and email both work on mobile (google pixel) and desktop.

image

image

**Comment by steveoh** [comment]
what do you experience?

**Comment by nathankota** [comment]
Oh, the red and blue must appear when one works and the other doesn't? I see the cloud icon do a little 360 then get the download and email.

**Comment by steveoh** [comment]
hmm ok..... weird. are there any possibly related console errors?

**Comment by nathankota** [comment]
no, it looks pretty normal

image

**Pull request merged**
